sudo: required
language: python
cache: pip
python:
    - "2.7"
services:
    - redis-server
install:
    - pip install --no-use-wheel lxml
    - pip install --allow-all-external -e .[test]
    - pip install flake8
    - pip install coveralls
script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - coverage run setup.py test
after_success:
    - coverage combine
    - coveralls
